### PR TITLE
C template

### PR DESCRIPTION
**Pull request by Robotnik08**
Template for the C programming language,
verified memory safe.

Has the same behauvior as the other templates.

### CODE REVIEW

**Comment by codevogel** [comment]
Seeing as the target audience for this repo is _new_ programmers, I think it'd make more sense to make use of something like [getline](https://linux.die.net/man/3/getline), reducing mental overhead.

e.g. something like https://stackoverflow.com/a/3501681/12094608

**Comment by Robotnik08** [comment]
the `getline` prototype is not available by default on non-posix systems (windows)

**Comment by codevogel** [comment]
> the `getline` prototype is not available by default on non-posix systems (windows)

The point of my comment was not to replace it with `getline` specifically, but rather to alter the code so it's a bit more beginner-friendly. I don't think many a newcomer will be able to understand what is happening here.

**Comment by Robotnik08** [comment]
I can reimplement the getline function and include it in a header, having it as a tool for the main file, 

does that sound like a good idea?

**Comment by Robotnik08** [comment]
> I can reimplement the getline function and include it in a header, having it as a tool for the main file,
> 
> does that sound like a good idea?

as well as other utils

**Comment by codevogel** [comment]
It might be worth using the [CS50 library](https://manual.cs50.io/) [(link 2)](https://github.com/cs50/libcs50)

**Comment by Robotnik08** [comment]
Mhmh, this might be worth looking into, but for now I will close this PR since I can't work on this at the moment

**Pull request closed without merging**
